### ISSUE TITLE
[Bug]: Fatal error in EdcHost.Games.Player.Trade

### ISSUE THREAD

**Issue by Spartan859** [THUASTA/EDCHost#19]
### Describe the bug

```c#
case IPlayer.CommodityKindType.HealthBoost:
    if (EmeraldCount >= (20 - MaxHealth))
    {
        EmeraldCount -= 20 - MaxHealth;
        MaxHealth += 1;
        return true;
    }
    /// Implement the logic for health boost
    /// You can perform the health boost operation here and update the player's status
    break;
```
At line 124.

MaxHealth is initially set to 20, so player can add its MaxHealth by 1 repeatedly through trade, and even gain Emeralds meanwhile.

Maybe "20 - MaxHealth" should be "20 + MaxHealth"?

### To Reproduce

-

### Expected behavior

-

**Comment by StevenC8661476** [comment]
"If a player's maximum health is $X$, then the value of health boost is $(X-20)$".
Therefore it should be `MaxHealth - 20`.
